### ISSUE TITLE
DIY 2.4G 20x20 RX build guide incorrect

### ISSUE THREAD

**Issue by mgtschida** [ExpressLRS/ExpressLRS-Hardware#20]
When building the DIY receiver at this link (https://github.com/ExpressLRS/ExpressLRS-Hardware/tree/master/PCB/2400MHz/RX_20x20/v2.0) I was unable to flash them upon build completion. Through the help of JamesK I removed the R5 resistor and was able to successfully flash the receivers using the ELRS Configurator. Hooking up to a flight controller, the receiver displayed a similar behavior to the EP1/2 where if hooked up to an F411 AIO the ESP is forced into bootloader mode. Adding a 470R resistor between the TX pin of the ESP-01F and 3.3V output of the regulator corrected this issue (thanks again to JamesK).

I've forked the readme and updated it as well as added a few images of the pullup resistor placement. https://github.com/mgtschida/ExpressLRS-Hardware/blob/master/PCB/2400MHz/RX_20x20/v2.0/README.md

**Comment by ucflumm** [comment]
I'm having same issues as you! In the diagram R3 is a 330R. 
Someone reverted the readme back to the incorrect one I have no clue why??

**Comment by kkbin505** [comment]
I experience the same issue, my method is to bridge the R3 and keep R5. Works well and no issue
![ELRS_RX_20_Issue](https://user-images.githubusercontent.com/43392862/148383159-194e745d-6168-4089-8c9d-e396d0bf6875.jpg)
.

**Comment by maybenikhil** [comment]
Updated the readme to match thank you so much!
