### ISSUE TITLE
Support for power select button and LED for 2.4 DIY Tx

### ISSUE THREAD

**Issue by RM-FPV** [ExpressLRS/ExpressLRS-Hardware#22]
Please add sbj to 2.4GHz Slim Tx boards.
It's needed for those who want to have manual power control.
It will also help to save an RC channel in case power control might be suggested to do that way.

Thank you!

**Comment by maybenikhil** [comment]
Power Control is done through MSP not through an RC Channel, so it doesnt take up any channels. Otherwise, manual power control can be achieved using a 5-way joystick and OLED
